// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV4xs0Y_aQ13dyXIN2NwBvSoNGMTVDmNI',
    appId: '1:136540710018:web:788d6c8ebad23ccadb409b',
    messagingSenderId: '136540710018',
    projectId: 'finalmp-aa3dd',
    authDomain: 'finalmp-aa3dd.firebaseapp.com',
    storageBucket: 'finalmp-aa3dd.firebasestorage.app',
    measurementId: 'G-LF4LQL8DKV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATs_qOxBLQfRif1W6gCRms25s0aMwAzXE',
    appId: '1:136540710018:android:d2ceb90aeaf78753db409b',
    messagingSenderId: '136540710018',
    projectId: 'finalmp-aa3dd',
    storageBucket: 'finalmp-aa3dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS6mqbpTPr0IhWgoMxNN76K7Tk7btbvrw',
    appId: '1:136540710018:ios:c804dad51ac3a92ddb409b',
    messagingSenderId: '136540710018',
    projectId: 'finalmp-aa3dd',
    storageBucket: 'finalmp-aa3dd.firebasestorage.app',
    iosClientId: '136540710018-nque3cok4u29329444efhm3bugef13n5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAS6mqbpTPr0IhWgoMxNN76K7Tk7btbvrw',
    appId: '1:136540710018:ios:c804dad51ac3a92ddb409b',
    messagingSenderId: '136540710018',
    projectId: 'finalmp-aa3dd',
    storageBucket: 'finalmp-aa3dd.firebasestorage.app',
    iosClientId: '136540710018-nque3cok4u29329444efhm3bugef13n5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBV4xs0Y_aQ13dyXIN2NwBvSoNGMTVDmNI',
    appId: '1:136540710018:web:ecb16bc472bf193ddb409b',
    messagingSenderId: '136540710018',
    projectId: 'finalmp-aa3dd',
    authDomain: 'finalmp-aa3dd.firebaseapp.com',
    storageBucket: 'finalmp-aa3dd.firebasestorage.app',
    measurementId: 'G-Z4G7799MBH',
  );
}
